
include:
  - template: Terraform/Base.gitlab-ci.yml

stages:
  - validate
  - build
  - deploy

fmt:
 extends: .terraform:fmt
 needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME